import {
  commandRegistry,
  assemblySchema,
  type CommandDefinition,
  type PayloadSchema,
} from '../core/commands';

const string: PayloadSchema = { type: 'string' };
function entry(
  name: string,
  description: string,
  properties: Record<string, PayloadSchema>,
  required: string[],
  mutates: boolean,
  payload: Record<string, unknown>,
): CommandDefinition {
  return {
    name,
    description,
    schema: {
      type: 'object',
      properties,
      required,
      additionalProperties: false,
    },
    mutates,
    examples: [{ name, payload }],
  };
}
export const applicationCommands = [
  entry(
    'performance.start',
    'Start a bounded performance recording, including PDF/cache stages and supported browser responsiveness measurements. No project changes.',
    {},
    [],
    false,
    {},
  ),
  entry(
    'performance.status',
    'Inspect whether performance recording is active and how much evidence is retained.',
    {},
    [],
    false,
    {},
  ),
  entry(
    'performance.stop',
    'Stop performance recording and return its report. Works while another command is running.',
    {},
    [],
    false,
    {},
  ),
  entry(
    'performance.export',
    'Export the current or last performance recording as JSON. No plan text or screenshots are included.',
    { path: string },
    [],
    false,
    { path: '/path/bluewing-performance.json' },
  ),
  entry(
    'help',
    'Get a short CLI introduction or the schema and examples for one command.',
    { command: string },
    [],
    false,
    { command: 'messages.send' },
  ),
  entry(
    'connect',
    'Identify the open project and get instructions for Wingman + chat or Chat only.',
    { mode: { type: 'string', enum: ['wingman', 'chat'] } },
    [],
    false,
    { mode: 'wingman' },
  ),
  entry(
    'messages.send',
    'Send a project message without changing the estimate or undo history.',
    {
      text: string,
      attachments: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: string,
            name: string,
            dataUrl: string,
            width: { type: 'number', minimum: 1 },
            height: { type: 'number', minimum: 1 },
          },
          required: ['id', 'name', 'dataUrl', 'width', 'height'],
          additionalProperties: false,
        },
      },
    },
    [],
    false,
    { text: 'Please review this detail.' },
  ),
  entry(
    'messages.read',
    'Read messages after a cursor; optionally wait up to 25000ms for delivery.',
    {
      after: { type: 'number', minimum: 0 },
      waitMs: { type: 'number', minimum: 0 },
    },
    [],
    false,
    { after: 0, waitMs: 25000 },
  ),
  entry(
    'messages.wait',
    'Wait for user input in Wingman. The native CLI quietly renews short waits, up to timeoutMs (default 300000). Stop on ended or project_changed.',
    {
      after: { type: 'number', minimum: 0 },
      timeoutMs: { type: 'number', minimum: 0 },
      waitToken: string,
    },
    [],
    false,
    { after: 0, timeoutMs: 300000 },
  ),
  entry(
    'wingman.inspect',
    'Inspect the Wingman visual presentation.',
    {},
    [],
    false,
    {},
  ),
  entry(
    'wingman.flash',
    'Expand and glow the Wingman corner preview.',
    {},
    [],
    false,
    {},
  ),
  entry(
    'wingman.annotate',
    'Replace local Wingman plan annotations and optional highlights.',
    {
      annotations: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            points: {
              type: 'array',
              items: {
                type: 'object',
                properties: { x: { type: 'number' }, y: { type: 'number' } },
                required: ['x', 'y'],
                additionalProperties: false,
              },
            },
            label: string,
            color: string,
          },
          required: ['points', 'label', 'color'],
          additionalProperties: false,
        },
      },
      highlightIds: { type: 'array', items: string },
    },
    ['annotations'],
    false,
    { annotations: [], highlightIds: [] },
  ),
  entry(
    'project.backup',
    'Save a separate recovery copy of the open desktop project. Existing files are never overwritten.',
    { path: string },
    [],
    false,
    {},
  ),
  entry(
    'snippet.render',
    'Export a saved highlighted snippet with sheet identity and coordinate mapping.',
    {
      id: string,
      caption: string,
      path: string,
      maxDimension: { type: 'number', minimum: 64 },
    },
    ['id', 'path'],
    false,
    { id: 'snippet-1', path: '/path/detail.png' },
  ),
  entry(
    'construction.render',
    'Render calculated construction as a depth-tested 3D PNG, up to 8192 pixels per side. Use a named view or explicit azimuth/elevation in radians. Returns the resolved camera and display mode for Wingman or another export.',
    {
      path: string,
      caption: string,
      width: { type: 'number', minimum: 64 },
      height: { type: 'number', minimum: 64 },
      geometryIds: { type: 'array', items: string },
      levelId: string,
      materialId: string,
      role: string,
      azimuth: { type: 'number' },
      elevation: { type: 'number', minimum: -Math.PI / 2 },
      view: {
        type: 'string',
        enum: ['isometric', 'top', 'front', 'back', 'left', 'right'],
      },
      zoom: { type: 'number', minimum: 0.01 },
      target: {
        type: 'object',
        properties: {
          x: { type: 'number' },
          y: { type: 'number' },
          z: { type: 'number' },
        },
        required: ['x', 'y', 'z'],
        additionalProperties: false,
      },
      span: { type: 'number', minimum: Number.MIN_VALUE },
      displayMode: { type: 'string', enum: ['solid', 'framing', 'xray'] },
    },
    ['path'],
    false,
    {
      path: '/path/framing.png',
      width: 1600,
      height: 1000,
      view: 'isometric',
      displayMode: 'framing',
    },
  ),
  entry(
    'library.inspect',
    'Read this device’s global assembly library, independent of the project.',
    {},
    [],
    false,
    {},
  ),
  entry(
    'library.put',
    'Save a global assembly. Existing project copies are unchanged; global edits have no project undo.',
    {
      assembly: assemblySchema,
      expectedLibraryRevision: { type: 'number', minimum: 0 },
    },
    ['assembly', 'expectedLibraryRevision'],
    true,
    {
      assembly: commandRegistry.find((entry) => entry.name === 'assembly.put')
        ?.examples[0]?.payload,
      expectedLibraryRevision: 0,
    },
  ),
  entry(
    'library.delete',
    'Delete a global assembly without changing project copies.',
    { id: string, expectedLibraryRevision: { type: 'number', minimum: 0 } },
    ['id', 'expectedLibraryRevision'],
    true,
    { id: 'assembly-1', expectedLibraryRevision: 0 },
  ),
  entry(
    'library.addStarters',
    'Add missing starter assemblies, including previously deleted starters. Preserve existing definitions and project copies.',
    { expectedLibraryRevision: { type: 'number', minimum: 0 } },
    ['expectedLibraryRevision'],
    true,
    { expectedLibraryRevision: 0 },
  ),
  entry(
    'assembly.import',
    'Copy a global assembly into this project with a new id and one undo step.',
    { libraryId: string, id: string },
    ['libraryId', 'id'],
    true,
    { libraryId: 'drywall-face', id: 'project-drywall' },
  ),
  entry(
    'project.create',
    'Create a new local project at a new path. Close the current project first.',
    { name: string, path: string },
    ['name', 'path'],
    true,
    { name: 'Estimate', path: '/path/estimate.bluewing' },
  ),
  entry(
    'project.open',
    'Open a local project. Close the current project first.',
    { path: string },
    ['path'],
    true,
    { path: '/path/estimate.bluewing' },
  ),
  entry(
    'project.close',
    'Close the project and clear session undo history.',
    {},
    [],
    true,
    {},
  ),
  entry(
    'project.import',
    'Import every page of a PDF in one undoable save.',
    { path: string },
    ['path'],
    true,
    { path: '/path/plans.pdf' },
  ),
  entry(
    'sheet.render',
    'Render a bounded PNG with page/pixel mappings using the workspace renderer.',
    {
      sheetId: string,
      caption: string,
      path: string,
      maxDimension: { type: 'number', minimum: 64 },
      mode: { type: 'string', enum: ['plan', 'takeoff', 'combined'] },
      highlightIds: { type: 'array', items: string },
      bounds: {
        type: 'object',
        properties: {
          x: { type: 'number' },
          y: { type: 'number' },
          width: { type: 'number', minimum: Number.MIN_VALUE },
          height: { type: 'number', minimum: Number.MIN_VALUE },
        },
        required: ['x', 'y', 'width', 'height'],
        additionalProperties: false,
      },
    },
    ['sheetId', 'path'],
    false,
    {
      sheetId: 'sheet-1',
      path: '/path/sheet.png',
      maxDimension: 2048,
      mode: 'combined',
    },
  ),
  entry(
    'web.inspect',
    'Read desktop bridge and cached web version information.',
    {},
    [],
    false,
    {},
  ),
  entry(
    'web.stage',
    'Download and verify a complete web release without activating it.',
    { manifestUrl: string },
    ['manifestUrl'],
    false,
    { manifestUrl: 'https://your-release-host/manifest.json' },
  ),
  entry(
    'web.activate',
    'Activate a staged web release while no project is open.',
    { version: string },
    ['version'],
    true,
    { version: '0.1.1' },
  ),
] as const;

/** UI and terminal discovery share the core registry and these native-session entries. */
export const registry = [...commandRegistry, ...applicationCommands];
